# Generated by Django 3.2.5 on 2022-03-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=128)),
                ('tag', models.CharField(choices=[('b', 'Bug'), ('f', 'Amélioration'), ('i', 'Tâche')], max_length=12)),
                ('priority', models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=7)),
                ('status', models.CharField(choices=[('td', 'To do'), ('ip', 'In progress'), ('d', 'Done')], max_length=8)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
