# Generated by Django 3.2.5 on 2022-03-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('back', 'Back-end'), ('front', 'Front-end'), ('ios', 'IOS'), ('android', 'Android')], max_length=7)),
            ],
        ),
    ]
