# Generated by Django 3.2.5 on 2022-03-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('author', 'Author'), ('contributor', 'Contributor')], max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('po', 'PO'), ('dev', 'Developer')], max_length=128)),
            ],
        ),
    ]
